# Generated by Django 5.2.1 on 2025-06-12 08:51
from django.db import migrations, models

import django_prosemirror.fields
import django_prosemirror.schema
import testapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_schema_with_default",
                    django_prosemirror.fields.ProsemirrorModelField(
                        default=testapp.models.get_default_full_content,
                        help_text=(
                            "Rich text field with all node types enabled and "
                            "default content"
                        ),
                        schema=(
                            django_prosemirror.schema.AllowedNodeType["STRONG"],
                            django_prosemirror.schema.AllowedNodeType["ITALIC"],
                            django_prosemirror.schema.AllowedNodeType["BLOCKQUOTE"],
                            django_prosemirror.schema.AllowedNodeType[
                                "HORIZONTAL_RULE"
                            ],
                            django_prosemirror.schema.AllowedNodeType["HEADING"],
                            django_prosemirror.schema.AllowedNodeType["IMAGE"],
                            django_prosemirror.schema.AllowedNodeType["LINK"],
                            django_prosemirror.schema.AllowedNodeType["HARD_BREAK"],
                            django_prosemirror.schema.AllowedNodeType["CODE"],
                            django_prosemirror.schema.AllowedNodeType["CODE_BLOCK"],
                        ),
                        verbose_name="Full Schema Rich Text",
                    ),
                ),
                (
                    "full_schema_nullable",
                    django_prosemirror.fields.ProsemirrorModelField(
                        blank=True,
                        default=None,
                        help_text=(
                            "Rich text field with all node types, allows null values"
                        ),
                        null=True,
                        schema=(
                            django_prosemirror.schema.AllowedNodeType["STRONG"],
                            django_prosemirror.schema.AllowedNodeType["ITALIC"],
                            django_prosemirror.schema.AllowedNodeType["BLOCKQUOTE"],
                            django_prosemirror.schema.AllowedNodeType[
                                "HORIZONTAL_RULE"
                            ],
                            django_prosemirror.schema.AllowedNodeType["HEADING"],
                            django_prosemirror.schema.AllowedNodeType["IMAGE"],
                            django_prosemirror.schema.AllowedNodeType["LINK"],
                            django_prosemirror.schema.AllowedNodeType["HARD_BREAK"],
                            django_prosemirror.schema.AllowedNodeType["CODE"],
                            django_prosemirror.schema.AllowedNodeType["CODE_BLOCK"],
                        ),
                        verbose_name="Full Schema (Nullable)",
                    ),
                ),
                (
                    "basic_text_only",
                    django_prosemirror.fields.ProsemirrorModelField(
                        blank=True,
                        default=testapp.models.get_empty_doc,
                        help_text="Minimal text field with no formatting options",
                        schema=[],
                        verbose_name="Basic Text Only",
                    ),
                ),
                (
                    "text_formatting_only",
                    django_prosemirror.fields.ProsemirrorModelField(
                        default=testapp.models.get_default_formatted_text,
                        help_text=(
                            "Text with basic formatting (bold, italic, code), no "
                            "block elements"
                        ),
                        schema=[
                            django_prosemirror.schema.AllowedNodeType["STRONG"],
                            django_prosemirror.schema.AllowedNodeType["ITALIC"],
                            django_prosemirror.schema.AllowedNodeType["CODE"],
                        ],
                        verbose_name="Text Formatting Only",
                    ),
                ),
                (
                    "headings_and_blocks",
                    django_prosemirror.fields.ProsemirrorModelField(
                        blank=True,
                        default=None,
                        help_text=(
                            "Document structure with headings, quotes, and basic "
                            "formatting"
                        ),
                        null=True,
                        schema=[
                            django_prosemirror.schema.AllowedNodeType["HEADING"],
                            django_prosemirror.schema.AllowedNodeType["BLOCKQUOTE"],
                            django_prosemirror.schema.AllowedNodeType[
                                "HORIZONTAL_RULE"
                            ],
                            django_prosemirror.schema.AllowedNodeType["STRONG"],
                            django_prosemirror.schema.AllowedNodeType["ITALIC"],
                        ],
                        verbose_name="Headings and Blocks (Nullable)",
                    ),
                ),
                (
                    "code_content_nullable",
                    django_prosemirror.fields.ProsemirrorModelField(
                        default=None,
                        help_text=(
                            "Technical content with inline and block code support"
                        ),
                        null=True,
                        schema=[
                            django_prosemirror.schema.AllowedNodeType["CODE"],
                            django_prosemirror.schema.AllowedNodeType["CODE_BLOCK"],
                            django_prosemirror.schema.AllowedNodeType["STRONG"],
                            django_prosemirror.schema.AllowedNodeType["ITALIC"],
                        ],
                        verbose_name="Code Content (Nullable)",
                    ),
                ),
            ],
        ),
    ]
