# Generated by Django 5.2.1 on 2025-07-01 14:16
# ruff: noqa: E501
from django.db import migrations, models

import django_prosemirror.fields
import django_prosemirror.schema.types
import testapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_schema_with_default",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=None,
                        allowed_node_types=None,
                        default=testapp.models.get_default_full_content,
                        help_text="Rich text field with all node types enabled and default content",
                        history=None,
                        tag_to_classes=None,
                        verbose_name="Full Schema Rich Text",
                    ),
                ),
                (
                    "full_schema_nullable",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=None,
                        allowed_node_types=None,
                        blank=True,
                        default=None,
                        help_text="Rich text field with all node types, allows null values",
                        history=None,
                        null=True,
                        tag_to_classes=None,
                        verbose_name="Full Schema (Nullable)",
                    ),
                ),
                (
                    "basic_text_only",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=[],
                        allowed_node_types=[
                            django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                        ],
                        blank=True,
                        default=testapp.models.get_empty_doc,
                        help_text="Minimal text field with no formatting options",
                        history=None,
                        tag_to_classes=None,
                        verbose_name="Basic Text Only",
                    ),
                ),
                (
                    "text_formatting_only",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=[
                            django_prosemirror.schema.types.MarkType["STRONG"],
                            django_prosemirror.schema.types.MarkType["ITALIC"],
                            django_prosemirror.schema.types.MarkType["CODE"],
                        ],
                        allowed_node_types=[
                            django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                        ],
                        default=testapp.models.get_default_formatted_text,
                        help_text="Text with basic formatting (bold, italic, code), no block elements",
                        history=None,
                        tag_to_classes=None,
                        verbose_name="Text Formatting Only",
                    ),
                ),
                (
                    "headings_and_blocks",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=[
                            django_prosemirror.schema.types.MarkType["STRONG"],
                            django_prosemirror.schema.types.MarkType["ITALIC"],
                        ],
                        allowed_node_types=[
                            django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                            django_prosemirror.schema.types.NodeType["HEADING"],
                            django_prosemirror.schema.types.NodeType["BLOCKQUOTE"],
                            django_prosemirror.schema.types.NodeType["HORIZONTAL_RULE"],
                        ],
                        blank=True,
                        default=None,
                        help_text="Document structure with headings, quotes, and basic formatting",
                        history=None,
                        null=True,
                        tag_to_classes=None,
                        verbose_name="Headings and Blocks (Nullable)",
                    ),
                ),
                (
                    "code_content_nullable",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=[
                            django_prosemirror.schema.types.MarkType["CODE"],
                            django_prosemirror.schema.types.MarkType["STRONG"],
                            django_prosemirror.schema.types.MarkType["ITALIC"],
                        ],
                        allowed_node_types=[
                            django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                            django_prosemirror.schema.types.NodeType["CODE_BLOCK"],
                        ],
                        default=None,
                        help_text="Technical content with inline and block code support",
                        history=None,
                        null=True,
                        tag_to_classes=None,
                        verbose_name="Code Content (Nullable)",
                    ),
                ),
            ],
        ),
    ]
