export enum SchemaNodesEnum {
    STRONG = "strong",
    ITALIC = "em",
    UNDERLINE = "underline",
    BLOCKQUOTE = "blockquote",
    HORIZONTAL_RULE = "horizontal_rule",
    HEADING = "heading",
    IMAGE = "image",
    LINK = "link",
    STRIKETHROUGH = "strikethrough",
    HARD_BREAK = "hard_break",
    CODE = "code",
    CODE_BLOCK = "code_block",
    ORDERED_LIST = "ordered_list",
    UNORDERED_LIST = "unordered_list",
    LIST_ITEM = "list_item",
    PARAGRAPH = "paragraph",
}
