import { NodeType, MarkType } from "../frontend/schema/types";

export const defaultArgs = {
    history: true,
    allowedMarks: [
        MarkType.CODE,
        MarkType.ITALIC,
        MarkType.LINK,
        MarkType.STRIKETHROUGH,
        MarkType.STRONG,
        MarkType.UNDERLINE,
    ],
    allowedNodes: [
        NodeType.BLOCKQUOTE,
        NodeType.BULLET_LIST,
        NodeType.CODE_BLOCK,
        NodeType.DOC,
        NodeType.HARD_BREAK,
        NodeType.HEADING,
        NodeType.HORIZONTAL_RULE,
        NodeType.IMAGE,
        NodeType.LIST_ITEM,
        NodeType.ORDERED_LIST,
        NodeType.PARAGRAPH,
        NodeType.TABLE,
        NodeType.TABLE_CELL,
        NodeType.TABLE_HEADER,
        NodeType.TABLE_ROW,
        NodeType.TEXT,
    ],
    classes: {
        paragraph: "story_classes",
        heading: "story_classes",
        image: "story_classes",
        link: "story_classes",
        blockquote: "story_classes",
        code_block: "story_classes",
        code: "story_classes",
        ordered_list: "story_classes",
        bullet_list: "story_classes",
        list_item: "story_classes",
        horizontal_rule: "story_classes",
    },
    resize: "none",
};
